symbol = "QQQ"
data_path = "../../data"
strategy = "stratcheck.strategies:BuyAndHoldStrategy"
initial_cash = 100000
timeframe = "1d"
bars_freq = "1d"
report_name = "qqq_buy_and_hold"
report_dir = "../../reports"

[cost_model]
type = "fixed_bps"
commission_bps = 2
slippage_bps = 1

[windows]
window_size = "6M"
step_size = "3M"

[strategy_params]
target_position_qty = 1.0
